name: 24h GitHub Activity Report

on:
  schedule:
    - cron: '0 19 * * *'
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Slack Notification Script
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          REPOS: ${{ secrets.REPOS }}
          HOURS: 27
        run: ./github-report/slack.sh
